-- Recuperando colunas especificas da tabela EMPLOYEES
SELECT  *
FROM    HR.EMPLOYEES;

SELECT  FIRST_NAME, LAST_NAME
FROM    HR.EMPLOYEES;

SELECT  FIRST_NAME, LAST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM    HR.EMPLOYEES;