-- VEJA A DIFERENCA DE RESULTADOS NOS INSTRUCOES ABAIXO, QUE RESULTARA APLICANDO OS OPERADORES DE PRECEDENCIA EM LUGARES DIFERENTES
SELECT  FIRST_NAME, LAST_NAME AS NAME,
        SALARY,
        SALARY + (SALARY/100 * 10)  AS "SAL_AUMENTO_10%"        
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 20;

SELECT  FIRST_NAME, LAST_NAME AS NAME,
        SALARY,
        (SALARY + SALARY/100) * 10  AS "SAL_AUMENTO_1_X_10"        
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 20;

-- UTILIZANDO O OPERADOR DE CONCATENACAO || + literal espaco em branco
SELECT  FIRST_NAME || ' ' || LAST_NAME AS NAME,
        JOB_ID,
        SALARY        
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 20;

-- UTILIZANDO O OPERADOR DE NOTACAO "q"
SELECT  FIRST_NAME || q'['s]' AS FIRST_NAME,
        JOB_ID,
        SALARY        
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 20;

