SELECT  EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 60
AND     JOB_ID = 'IT_PROG'
OR      JOB_ID = 'AD_VP';

-- utilize parenteses para mudar precedencia 
SELECT  EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM    HR.EMPLOYEES
WHERE   DEPARTMENT_ID = 60
AND     (JOB_ID = 'IT_PROG'
OR      JOB_ID = 'AD_VP');