SELECT * FROM tb_clientes;

SELECT * FROM tb_clientes WHERE IDADE = 22;
//IGUAL A 22
SELECT * FROM tb_clientes WHERE IDADE < 22;
//MAIOR QUE 22
SELECT * FROM tb_clientes WHERE IDADE > 22;
//MENOR QUE 22
SELECT * FROM tb_clientes WHERE IDADE <> 22;
//DIFERENTE DE = 22
SELECT * FROM tb_clientes WHERE NOME >= 'Fernado Calvacante';
SELECT * FROM tb_clientes WHERE NOME <> 'Fernado Calvacante';

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.008;

SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008;
SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;