//FILTRANDO DATAS
SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE ('07/10/95', 'DD/MM/YY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO > TO_DATE ('07/10/95', 'DD/MM/YY');

SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO,'M') = 10;
//SELECIONA AS DATAS DE NASCIMENTO DE OUTUBRO


SELECT * FROM TABELA_DE_VENDEDORES WHERE TO_CHAR(DATA_ADMISSAO, 'YYYY') >= '2016';